{
 "title": "Story Dashboard",
 "tags": [ "story" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cometbft_consensus_height,chain_id)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(cometbft_consensus_height{chain_id=\"$chain_id\"},instance)"
    }
   },
   {
    "name": "geth_instance",
    "label": "geth_instance",
    "query": {
     "query": "label_values(blobpool_add_gapped,instance)"
    }
   },
   {
    "name": "server_health_instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   {
    "name": "hex_address",
    "query": {
     "query": "label_values(cometbft_consensus_validator_power, validator_address)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Blockchain overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 }, "options": { "content": " " } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{instance=\"$instance\"} - cometbft_consensus_missing_validators{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokenomics",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{instance=\"$instance\"}",
     "legendFormat": "Bonded tokens"
    },
    {
     "expr": "story_chain_total_supply / 1000000",
     "legendFormat": "Total tokens"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_sum{chain_id=\"$chain_id\", instance=\"$instance\"} / cometbft_consensus_block_interval_seconds_count{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Validators Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting Power of Missing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators_power{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{instance=\"$instance\"}",
     "legendFormat": "num txs"
    },
    {
     "expr": "cometbft_consensus_missing_validators",
     "legendFormat": "num missing validators"
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "cometbft_mempool_size{instance=\"$instance\"}",
     "legendFormat": "num of uncommitted txs"
    },
    {
     "expr": "rate(cometbft_mempool_failed_txs{instance=\"$instance\"} [5m])",
     "legendFormat": "failed tx rate"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "p2p Peers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{instance=\"$instance\"}",
     "legendFormat": "num peers"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (rate(cometbft_p2p_peer_receive_bytes_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "peer {{peer_id}}"
    }
   ]
  },
  {
   "title": "рџ‘ЁвЂЌрџ’» Validator Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_blocksync_syncing{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Jailed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "story_chain_validator_info{hex_address=\"$hex_address\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 18, "x": 6, "y": 20 },
     "targets": [
      {
       "expr": "story_chain_validator_info{hex_address=\"$hex_address\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "story_chain_validator_info{hex_address=\"$hex_address\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blocks [24h]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(cometbft_consensus_height{instance=\"$instance\"}[24h])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Missed blocks [24h]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(cometbft_consensus_validator_missed_blocks[24h])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blocks [5m]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(cometbft_consensus_height{instance=\"$instance\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Missed blocks [5m]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(cometbft_consensus_validator_missed_blocks[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Missed blocks",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 66 },
     "targets": [
      {
       "expr": "cometbft_consensus_validator_missed_blocks",
       "legendFormat": "missed_blocks"
      }
     ]
    },
    {
     "title": "Uptime [24h]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "(1 - $A / $B) * 100", "type": "math" }
     ]
    },
    {
     "title": "Uptime [5m]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "(1 - $A / $B) * 100", "type": "math" }
     ]
    },
    {
     "title": "Mempool",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
     "targets": [
      {
       "expr": "cometbft_mempool_active_outbound_connections{instance=\"$instance\"}",
       "legendFormat": "Connections"
      },
      {
       "expr": "rate(cometbft_mempool_failed_txs{instance=\"$instance\"} [5m])",
       "legendFormat": "failed tx rate"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Last signed height",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "cometbft_consensus_validator_last_signed_height",
       "legendFormat": "signed_height"
      }
     ]
    },
    {
     "title": "Validator Power",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "cometbft_consensus_validator_power",
       "legendFormat": "validator_power"
      }
     ]
    }
   ]
  },
  {
   "title": "рџ“¦ Block parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Size",
     "type": "stat",
     "description": "The amount of data contained in the last block (in bytes)",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_consensus_block_size_bytes{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Interval",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 5, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(cometbft_consensus_block_interval_seconds_bucket{chain_id=\"$chain_id\"}[5m])) by (le))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Block Time Rate (sec)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(cometbft_consensus_block_interval_seconds_sum[1m]) - rate(cometbft_consensus_block_interval_seconds_count[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Timing for each ABCI method",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(cometbft_abci_connection_method_timing_seconds_bucket{chain_id=\"$chain_id\"}[5m])) by (le, method))\n",
       "legendFormat": "{{Method}}"
      }
     ]
    }
   ]
  },
  { "title": "в›Ѕ Transactions & Gas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Transactions ",
   "type": "stat",
   "description": "Counts the transactions in the latest block.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{instance=\"$instance\"}",
     "legendFormat": "txs"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 22 },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "cosmos_tx_successful{instance=\"$instance\"}",
     "legendFormat": "TXs"
    }
   ]
  },
  {
   "title": "Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 22 },
   "targets": [
    { "expr": "cosmos_tx_count", "legendFormat": "TXs" }
   ]
  },
  {
   "title": "Gas Fee",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_tx_gas_used{instance=\"$instance\"}",
     "legendFormat": "gas_fee"
    }
   ]
  },
  {
   "title": "Gas Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 3, "y": 27 },
   "targets": [
    { "expr": "cosmos_tx_gas_used", "legendFormat": "gas" }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{instance=\"$geth_instance\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{instance=\"$geth_instance\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{instance=\"$geth_instance\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=\"$geth_instance\"}[1m])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(txpool_invalid{instance=\"$geth_instance\"}[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(txpool_underpriced{instance=\"$geth_instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=\"$geth_instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=\"$geth_instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=\"$geth_instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=\"$geth_instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=\"$geth_instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=\"$geth_instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=\"$geth_instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{job=\"geth_node\", instance=\"$geth_instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  { "title": "рџЄ™ Staking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "MInted Tokens",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "cosmos_minted_tokens", "legendFormat": "tokens" }
   ]
  },
  {
   "title": "Staking Delegate Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_tx_msg__cosmos_staking_v1beta1_MsgDelegate",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Staking Undelegate Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_tx_msg__cosmos_staking_v1beta1_MsgUndelegate",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Staking Reward Queue Depth",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "evmstaking_reward_queue_depth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "вљ™пёЏ GETH Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "geth version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 162 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "geth_info{instance=\"$geth_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(p2p_ingress{instance=\"$geth_instance\"}[1m])",
       "legendFormat": "ingress"
      },
      {
       "expr": "rate(p2p_egress{instance=\"$geth_instance\"}[1m])",
       "legendFormat": "egress"
      }
     ]
    },
    {
     "title": "Peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "p2p_peers{instance=\"$geth_instance\"}",
       "legendFormat": "peers"
      },
      {
       "expr": "p2p_peers_inbound{instance=\"$geth_instance\"}",
       "legendFormat": "peers_inbound"
      },
      { "expr": "p2p_peers_outbound", "legendFormat": "peers_outbound" },
      {
       "expr": "rate(p2p_dials{instance=\"$geth_instance\"}[1m])",
       "legendFormat": "dials"
      },
      {
       "expr": "rate(p2p_serves{instance=\"$geth_instance\"}[1m])",
       "legendFormat": "serves"
      }
     ]
    },
    {
     "title": "Latest header",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 164 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chain_head_header{instance=\"$geth_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latest receipt",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 166 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chain_head_receipt{instance=\"$geth_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latest block",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 168 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chain_head_block{instance=\"$geth_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block processing",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "chain_validation{quantile=\"0.5\", instance=\"$geth_instance\"}",
       "legendFormat": "validation (q=$quantile)"
      },
      {
       "expr": "chain_validation{quantile=\"0.5\", instance=\"$geth_instance\"}",
       "legendFormat": "commit (q=$quantile)"
      },
      {
       "expr": "chain_validation{quantile=\"0.5\", instance=\"$geth_instance\"}",
       "legendFormat": "account read (q=$quantile)"
      },
      {
       "expr": "chain_validation{quantile=\"0.5\", instance=\"$geth_instance\"}",
       "legendFormat": "account update (q=$quantile)"
      },
      {
       "expr": "chain_validation{quantile=\"0.5\", instance=\"$geth_instance\"}",
       "legendFormat": "account hashe (q=$quantile)"
      },
      {
       "expr": "chain_validation{quantile=\"0.5\", instance=\"$geth_instance\"}",
       "legendFormat": "account commit (q=$quantile)"
      },
      {
       "expr": "chain_validation{quantile=\"0.5\", instance=\"$geth_instance\"}",
       "legendFormat": "storage read (q=$quantile)"
      },
      {
       "expr": "chain_validation{quantile=\"0.5\", instance=\"$geth_instance\"}",
       "legendFormat": "storage update (q=$quantile)"
      },
      {
       "expr": "chain_validation{quantile=\"0.5\", instance=\"$geth_instance\"}",
       "legendFormat": "storage hashe (q=$quantile)"
      },
      {
       "expr": "chain_validation{quantile=\"0.5\", instance=\"$geth_instance\"}",
       "legendFormat": "storage commit (q=$quantile)"
      }
     ]
    },
    {
     "title": "Data rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(eth_db_chaindata_disk_read{instance=\"$geth_instance\"}[1m])",
       "legendFormat": "leveldb read"
      },
      {
       "expr": "rate(eth_db_chaindata_disk_write{instance=\"$geth_instance\"}[1m])",
       "legendFormat": "leveldb write"
      },
      {
       "expr": "rate(eth_db_chaindata_ancient_read{instance=\"$geth_instance\"}[1m])",
       "legendFormat": "ancient read"
      },
      {
       "expr": "rate(eth_db_chaindata_ancient_write{instance=\"$geth_instance\"}[1m])",
       "legendFormat": "ancient write"
      }
     ]
    },
    {
     "title": "Session totals",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eth_db_chaindata_disk_read{instance=\"$geth_instance\"}",
       "legendFormat": "leveldb read"
      },
      {
       "expr": "eth_db_chaindata_disk_write{instance=\"$geth_instance\"}",
       "legendFormat": "leveldb write"
      },
      {
       "expr": "eth_db_chaindata_ancient_read{instance=\"$geth_instance\"}",
       "legendFormat": "ancient read"
      },
      {
       "expr": "eth_db_chaindata_ancient_write{instance=\"$geth_instance\"}",
       "legendFormat": "ancient write"
      }
     ]
    },
    {
     "title": "Storage size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eth_db_chaindata_disk_size{instance=\"$geth_instance\"}",
       "legendFormat": "leveldb"
      },
      {
       "expr": "eth_db_chaindata_ancient_size{instance=\"$geth_instance\"}",
       "legendFormat": "ancient"
      }
     ]
    }
   ]
  },
  {
   "title": "рџ’ѕ System Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{instance=\"$server_health_instance\", mode=\"idle\"}[1m])) * 100)",
       "legendFormat": "CPU"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$server_health_instance\"} / (node_memory_MemTotal_bytes{instance=\"$server_health_instance\"})))* 100",
       "legendFormat": "RAM"
      },
      {
       "expr": "(1 - (node_memory_SwapFree_bytes{instance=\"$server_health_instance\"} / node_memory_SwapTotal_bytes{instance=\"$server_health_instance\"})) * 100",
       "legendFormat": "SWAP"
      },
      {
       "expr": "100 - (node_filesystem_free_bytes{instance=\"$server_health_instance\", device=\"/dev/sda2\"} * 100 / node_filesystem_size_bytes{instance=\"$server_health_instance\", device=\"/dev/sda2\"})",
       "legendFormat": "Disk"
      },
      {
       "expr": "100 - (node_filesystem_free_bytes{instance=\"$server_health_instance\", device=\"/dev/sda1\"} * 100 / node_filesystem_size_bytes{instance=\"$server_health_instance\", device=\"/dev/sda1\"})",
       "legendFormat": "Boot"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load15{instance=\"$server_health_instance\"})/count(count(node_cpu_seconds_total) by (cpu)) * 100  "
      }
     ]
    },
    {
     "title": "Disk",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(device) (node_filesystem_avail_bytes)",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total) by (cpu))"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds-node_boot_time_seconds{instance=\"$server_health_instance\"}"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$server_health_instance\", mountpoint=\"/\",fstype!=\"rootfs\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$server_health_instance\"}"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$server_health_instance\"}"
      }
     ]
    },
    {
     "title": "CPU ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server_health_instance\", mode=\"system\"}[1m])))/(  sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server_health_instance\"}[1m])))\r\n",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server_health_instance\", mode=\"user\"}[1m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$server_health_instance\"}[1m])))",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server_health_instance\", mode=\"iowait\"}[1m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$server_health_instance\"}[1m])))",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server_health_instance\", mode=~\".*irq\"}[1m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$server_health_instance\"}[1m])))",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server_health_instance\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[1m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$server_health_instance\"}[1m])))",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server_health_instance\", mode=\"idle\"}[1m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[1m])))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$server_health_instance\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "(\r\n  sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server_health_instance\", mode=\"system\"}[1m]))\r\n)\r\n/\r\n(\r\n  sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server_health_instance\"}[1m]))\r\n)\r\n",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$server_health_instance\"} + node_memory_Buffers_bytes{instance=\"$server_health_instance\"} + node_memory_SReclaimable_bytes{instance=\"$server_health_instance\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$server_health_instance\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$server_health_instance\"} - node_memory_SwapFree_bytes{instance=\"$server_health_instance\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "timeseries",
     "description": "Used Root FS",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$server_health_instance\", mountpoint=\"/\", fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$server_health_instance\", mountpoint=\"/\", fstype!=\"rootfs\"})\r\n"
      }
     ]
    },
    {
     "title": "Disk (Read/Write)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(system_disk_readbytes{instance=\"$geth_instance\"}[5m])",
       "legendFormat": "read"
      },
      {
       "expr": "rate(system_disk_writebytes{instance=\"$geth_instance\"}[5m])",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Disk Read time [ms]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 184 },
     "targets": [
      {
       "expr": "sum by(device) (rate(node_disk_read_time_seconds_total[1m]) * 1000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Write time [ms]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 184 },
     "targets": [
      {
       "expr": "sum by(device) (rate(node_disk_write_time_seconds_total[1m]) * 1000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Receive Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by(device) (irate(node_network_receive_bytes_total[1m])) * 8",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by(device) (irate(node_network_transmit_bytes_total[1m]) * 8)",
       "legendFormat": "trans {{device}} "
      }
     ]
    }
   ]
  }
 ]
}